name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

      - name: Test
        run: |-
          docker build -t rallycoding/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true rallycoding/react-test npm test

      - name: Build
        run: |-
          docker build -t adrianchinjen/multi-client ./client
          docker build -t adrianchinjen/multi-nginx ./nginx
          docker build -t adrianchinjen/multi-server ./server
          docker build -t adrianchinjen/multi-worker ./worker
          

      - name: Push
        run: |-
          docker push adrianchinjen/multi-client
          docker push adrianchinjen/multi-nginx
          docker push adrianchinjen/multi-server
          docker push adrianchinjen/multi-worker

      # - run: docker build -t rallycoding/react-test -f ./client/Dockerfile.dev ./client
      # - run: docker run -e CI=true rallycoding/react-test npm test

      # - run: docker build -t rallycoding/multi-client ./client
      # - run: docker build -t rallycoding/multi-nginx ./nginx
      # - run: docker build -t rallycoding/multi-server ./server
      # - run: docker build -t rallycoding/multi-worker ./worker

      # - run: docker push rallycoding/multi-client
      # - run: docker push rallycoding/multi-nginx
      # - run: docker push rallycoding/multi-server
      # - run: docker push rallycoding/multi-worker
